# Generated by Django 4.0.3 on 2022-04-03 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, choices=[('menstrualHeath', 'Menstrual Health'), ('yoga', 'Yoga'), ('skincare', 'Skin Care'), ('fitness', 'Fitness'), ('mentalHealth', 'Mental Health'), ('diet', 'Diet'), ('sleep', 'Sleep'), ('relationships', 'Relationships'), ('pcos', 'PCOS'), ('sexLife', 'Sex Life'), ('pms', 'PMS')], default='menstrualHealth', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
